Sync package folder from Actions

diff --git a/luci-app-adguardhome/root/etc/init.d/AdGuardHome b/luci-app-adguardhome/root/etc/init.d/AdGuardHome
--- a/luci-app-adguardhome/root/etc/init.d/AdGuardHome
+++ b/luci-app-adguardhome/root/etc/init.d/AdGuardHome
@@ -7,6 +7,7 @@ STOP=01
 
 CONFIGURATION=AdGuardHome
 CRON_FILE=/etc/crontabs/root
+GFWSET="gfwlist"
 EXTRA_COMMANDS="do_redirect testbackup test_crontab force_reload isrunning"
 EXTRA_HELP="        do_redirect 0 or 1\
         testbackup backup or restore\
@@ -47,9 +48,13 @@ stop_forward_dnsmasq()
 	fi
 
 	uci del_list dhcp.@dnsmasq[0].server=$addr 2>/dev/null
+	rcauto="/tmp/resolv.conf.auto"
+	if [ -e "/tmp/resolv.conf.d/resolv.conf.auto" ]; then
+		rcauto="/tmp/resolv.conf.d/resolv.conf.auto"
+	fi
 	addrlist="`uci get dhcp.@dnsmasq[0].server 2>/dev/null`"
 	if [ -z "$addrlist" ] ; then
-		uci set dhcp.@dnsmasq[0].resolvfile=/tmp/resolv.conf.auto 2>/dev/null
+		uci set dhcp.@dnsmasq[0].resolvfile="$rcauto" 2>/dev/null
 		uci delete dhcp.@dnsmasq[0].noresolv 2>/dev/null
 	fi
 	uci commit dhcp
@@ -58,67 +63,35 @@ stop_forward_dnsmasq()
 
 set_iptable()
 {
-	local ipv6_server=$1
-	local tcp_server=$2
-	uci -q batch <<-EOF >/dev/null 2>&1
-  delete firewall.AdGuardHome
-	set firewall.AdGuardHome=include
-	set firewall.AdGuardHome.type=script
-	set firewall.AdGuardHome.path=/usr/share/AdGuardHome/firewall.start
-	set firewall.AdGuardHome.reload=1
-	commit firewall
-EOF
-
-	IPS="`ifconfig | grep "inet addr" | grep -v ":127" | grep "Bcast" | awk '{print $2}' | awk -F : '{print $2}'`"
-	for IP in $IPS
-	do
-		if [ "$tcp_server" == "1" ]; then
-			iptables -t nat -A PREROUTING -p tcp -d $IP --dport 53 -j REDIRECT --to-ports $AdGuardHome_PORT >/dev/null 2>&1
-		fi
-		iptables -t nat -A PREROUTING -p udp -d $IP --dport 53 -j REDIRECT --to-ports $AdGuardHome_PORT >/dev/null 2>&1
-	done
-
-	if [ "$ipv6_server" == 0 ]; then
-		return
+	section=$(uci add firewall redirect)
+	if [ -z "$section" ]; then
+		echo "failed to add redirect rule."
+		exit 1
 	fi
-
-	IPS="`ifconfig | grep "inet6 addr" | grep -v " fe80::" | grep -v " ::1" | grep "Global" | awk '{print $3}'`"
-	for IP in $IPS
-	do
-		if [ "$tcp_server" == "1" ]; then
-			ip6tables -t nat -A PREROUTING -p tcp -d $IP --dport 53 -j REDIRECT --to-ports $AdGuardHome_PORT >/dev/null 2>&1
-		fi
-		ip6tables -t nat -A PREROUTING -p udp -d $IP --dport 53 -j REDIRECT --to-ports $AdGuardHome_PORT >/dev/null 2>&1
-	done
-
+	uci set firewall.$section.target="DNAT"
+	uci set firewall.$section.name="AdGuard Home"
+	uci set firewall.$section.src="lan"
+	uci set firewall.$section.src_dport="53"
+	uci set firewall.$section.dest_port="$AdGuardHome_PORT"
+	uci commit firewall
+	/etc/init.d/firewall reload
+	echo "firewall rules updated."
 }
 
 clear_iptable()
 {
-	uci -q batch <<-EOF >/dev/null 2>&1
-  delete firewall.AdGuardHome
-	commit firewall
-EOF
-	local OLD_PORT="$1"
-	local ipv6_server=$2
-	IPS="`ifconfig | grep "inet addr" | grep -v ":127" | grep "Bcast" | awk '{print $2}' | awk -F : '{print $2}'`"
-	for IP in $IPS
-	do
-		iptables -t nat -D PREROUTING -p udp -d $IP --dport 53 -j REDIRECT --to-ports $OLD_PORT >/dev/null 2>&1
-		iptables -t nat -D PREROUTING -p tcp -d $IP --dport 53 -j REDIRECT --to-ports $OLD_PORT >/dev/null 2>&1
-	done
-
-	if [ "$ipv6_server" == 0 ]; then
-		return
+	redirects=$(uci show firewall | grep "AdGuard Home" | awk -F".name" '{print $1}')
+	if [ -z "$redirects" ]; then
+		echo "no redirect rules found."
+	else
+		for redirect in $redirects; do
+			uci delete $redirect
+			echo "deleted redirect rule: $redirect"
+		done
+		uci commit firewall
+		/etc/init.d/firewall reload
+		echo "firewall rules updated."
 	fi
-	echo "warn ip6tables nat mod is needed"
-	IPS="`ifconfig | grep "inet6 addr" | grep -v " fe80::" | grep -v " ::1" | grep "Global" | awk '{print $3}'`"
-	for IP in $IPS
-	do
-		ip6tables -t nat -D PREROUTING -p udp -d $IP --dport 53 -j REDIRECT --to-ports $OLD_PORT >/dev/null 2>&1
-		ip6tables -t nat -D PREROUTING -p tcp -d $IP --dport 53 -j REDIRECT --to-ports $OLD_PORT >/dev/null 2>&1
-	done
-
 }
 
 service_triggers() {
@@ -183,7 +156,7 @@ rm_port53()
 	config_editor "dns.port" "$dnsmasq_port" "$configpath"
 	uci set dhcp.@dnsmasq[0].port="53"
 	uci commit dhcp
-	/etc/init.d/dnsmasq reload
+	/etc/init.d/dnsmasq restart
 }
 
 use_port53()
@@ -203,7 +176,7 @@ use_port53()
 	config_editor "dns.port" "53" "$configpath"
 	uci set dhcp.@dnsmasq[0].port="$AdGuardHome_PORT"
 	uci commit dhcp
-	/etc/init.d/dnsmasq reload
+	/etc/init.d/dnsmasq restart
 }
 do_redirect()
 {
@@ -239,7 +212,7 @@ _do_redirect()
 	if [ "$old_redirect" != "$redirect" ] || [ "$old_port" != "$AdGuardHome_PORT" ] || [ "$old_enabled" = "1" -a "$enabled" = "0" ]; then
 		if [ "$old_redirect" != "none" ]; then
 			if [  "$old_redirect" == "redirect" -a "$old_port" != "0" ]; then
-				clear_iptable "$old_port" "$ipv6_server"
+				clear_iptable
 			elif [ "$old_redirect" == "dnsmasq-upstream" ]; then
 				stop_forward_dnsmasq "$old_port"
 			elif [ "$old_redirect" == "exchange" ]; then
@@ -248,7 +221,7 @@ _do_redirect()
 		fi
 	elif [ "$old_enabled" = "1" -a "$enabled" = "1" ]; then
 		if [  "$old_redirect" == "redirect" -a "$old_port" != "0" ]; then
-			clear_iptable "$old_port" "$ipv6_server"
+			clear_iptable
 		fi
 	fi
 	uci delete AdGuardHome.@AdGuardHome[0].old_redirect 2>/dev/null
@@ -263,7 +236,7 @@ _do_redirect()
 		return 1
 	fi
 	if [ "$redirect" = "redirect" ]; then
-		set_iptable $ipv6_server $tcp_server
+		set_iptable
 	elif [ "$redirect" = "dnsmasq-upstream" ]; then
 		set_forward_dnsmasq "$AdGuardHome_PORT"
 	elif [ "$redirect" == "exchange" -a "$(uci get dhcp.@dnsmasq[0].port 2>/dev/null)" == "53" ]; then
@@ -313,6 +286,7 @@ get_filesystem()
 
 config_editor()
 {
+	[ -n "$3" -a -f $3 ] || return
 	awk -v yaml="$1" -v value="$2" -v file="$3" -v ro="$4" '
 	BEGIN{split(yaml,part,"\.");s="";i=1;l=length(part);}
     {
@@ -402,6 +376,7 @@ start_service() {
 		uci set $CONFIGURATION.$CONFIGURATION.hashpass=""
 	fi
 	local enabled
+	local ipst=0
 	config_get_bool enabled $CONFIGURATION enabled 0
 	# update crontab
 	do_crontab
@@ -411,12 +386,16 @@ start_service() {
 	fi
 	#what need to do before reload
 	config_get workdir $CONFIGURATION workdir "/usr/bin/AdGuardHome"
-
+	grep -q "ipset.txt" $configpath 2>/dev/null && ipst=1
+	if [ $ipst -eq 1 ];then
+		ipset list $GFWSET >/dev/null 2>&1 || ipset create $GFWSET hash:ip 2>/dev/null
+	fi
 	config_get backupfile $CONFIGURATION backupfile ""
 	mkdir -p $workdir/data
 	if [ -n "$backupfile" ] && [ ! -d "$workdir/data" ]; then
 		restore
 	fi
+
 	# for overlay data-stk-oo not suppport
 	local cwdfs=$(get_filesystem $workdir)
 	echo "workdir is a $cwdfs filesystem"
@@ -479,7 +458,7 @@ start_service() {
 		_do_redirect 1
 	else
 		_do_redirect 0
-		config_get "redirect" "AdGuardHome" "redirect" "none"
+		config_get "redirect" $CONFIGURATION "redirect" "none"
 		if [ "$redirect" != "none" ]; then
 			procd_open_instance "waitconfig"
 			procd_set_param command "/usr/share/AdGuardHome/watchconfig.sh"
@@ -577,6 +556,11 @@ do_crontab(){
 	findstr="/usr/share/AdGuardHome/gfw2adg.sh"
 	default="30 3 * * * /usr/share/AdGuardHome/gfw2adg.sh"
 	[ "$enabled" == "0" ] || [ "${crontab//autogfw/}" == "$crontab" ] && cronenable=0 || cronenable=1
+	crontab_editor
+
+	findstr="/usr/share/AdGuardHome/gfwipset2adg.sh"
+	default="31 3 * * * /usr/share/AdGuardHome/gfwipset2adg.sh"
+	[ "$enabled" == "0" ] || [ "${crontab//autogfwipset/}" == "$crontab" ] && cronenable=0 || cronenable=1
 	crontab_editor
 	[ "$cronreload" -gt 0 ] && /etc/init.d/cron restart
 	#[ "$commit" -gt 0 ] && uci commit AdGuardHome
