Update Sync.yml

diff --git a/.github/workflows/Sync.yml b/.github/workflows/Sync.yml
--- a/.github/workflows/Sync.yml
+++ b/.github/workflows/Sync.yml
@@ -18,16 +18,25 @@ jobs:
         sudo -E apt-get update -y
         sudo -E apt-get install -y subversion rsync
     - name: Get Source
+      id: check
       run: |
+        DLurl=(
+          "git clone --depth=1 https://github.com/ThingsWhy/luci-app-adguardhome.git"
+          "svn export https://github.com/sbwml/luci-app-alist/trunk/luci-app-alist"
+          "svn export https://github.com/linkease/nas-packages/trunk/network/services/ddnsto"
+          "svn export https://github.com/linkease/nas-packages-luci/trunk/luci/luci-app-ddnsto"
+          "svn export https://github.com/gdy666/luci-app-lucky/trunk/luci-app-lucky && sed -i 's/^#LUCI_DEPENDS:=+lucky/LUCI_DEPENDS:=+lucky/' luci-app-lucky/Makefile"
+          "svn export https://github.com/gdy666/luci-app-lucky/trunk/lucky"
+        )
         cd "/home/runner"
         mkdir package && cd package
-        git clone --depth=1 https://github.com/ThingsWhy/luci-app-adguardhome.git
-        svn export https://github.com/sbwml/luci-app-alist/trunk/luci-app-alist
-        svn export https://github.com/linkease/nas-packages/trunk/network/services/ddnsto
-        svn export https://github.com/linkease/nas-packages-luci/trunk/luci/luci-app-ddnsto
-        svn export https://github.com/gdy666/luci-app-lucky/trunk/luci-app-lucky && sed -i 's/^#LUCI_DEPENDS:=+lucky/LUCI_DEPENDS:=+lucky/' luci-app-lucky/Makefile
-        svn export https://github.com/gdy666/luci-app-lucky/trunk/lucky
+        for url in "${DLurl[@]}"; do
+          if ! eval "$url"; then
+            echo "DL=Failed" >> $GITHUB_OUTPUT
+          fi
+        done
     - name: Sync package folder to upstream repo
+      if: steps.check.outputs.DL != 'Failed'
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
@@ -48,8 +57,6 @@ jobs:
         else
           echo "No Changes"
         fi
-    - name: CLean
-      run: |
         rm -f /home/runner/.ssh/id_rsa
     - name: Delete old workflow runs
       uses: Mattraks/delete-workflow-runs@v2
